## Importando Bibliotecas / criando queryes

In [2]:
import pandas as pd
import numpy as np
import sqlite3

conexao = sqlite3.connect('../varejo.db')

query_ecomerce = "SELECT * FROM tb_vendas_consolidada WHERE CANAL_VENDA = 'E-commerce'"
query_dados_consolidados =  "SELECT * FROM tb_vendas_consolidada"

def formatar(valor):
  valor = f'R$ {valor:,.2f}'
  return valor

#### Exportando dados das Vendas Online para vendas_ecommerce_limpo.json

In [3]:
df_ecommerce = pd.read_sql(query_ecomerce, conexao)

df_ecommerce.to_json('../data/vendas_ecommerce_limpo.json', index = False)

#### Análises - 1 Faturamento TOTAL

In [4]:
df_vendas = pd.read_sql(query_dados_consolidados, conexao)

total_vendas = df_vendas['TOTAL_VENDA'].sum()
total_qtd = df_vendas['QTD'].sum()

tabela_total = pd.DataFrame({'Faturamento Total': [total_vendas]})

tabela_total['QTD Vendidos'] = total_qtd

ticket_medio = tabela_total['Faturamento Total'] / tabela_total['QTD Vendidos']

tabela_total['Ticket Médio'] = ticket_medio

tabela_total['Faturamento Total'] = tabela_total['Faturamento Total'].apply(formatar)
tabela_total['Ticket Médio'] = tabela_total['Ticket Médio'].apply(formatar)


display(tabela_total)

  Faturamento Total  QTD Vendidos Ticket Médio
0       R$ 4,431.70            66     R$ 67.15

#### Análises - 1 Faturamento Por Canal de Venda

In [5]:
metricas_canal_venda = df_vendas[['CANAL_VENDA','TOTAL_VENDA']].groupby('CANAL_VENDA').sum().sort_values(by= 'TOTAL_VENDA', ascending = False).reset_index()
metricas_canal_venda['TOTAL_VENDA'] = metricas_canal_venda['TOTAL_VENDA'].apply(formatar)

display(metricas_canal_venda)

   CANAL_VENDA  TOTAL_VENDA
0  Loja Física  R$ 2,865.60
1   E-commerce  R$ 1,566.10